#!/bin/bash
#SBATCH -J darwinjob
#SBATCH -A carvalho-sl3
#SBATCH --nodes=16
#SBATCH --ntasks=16
#SBATCH --cpus-per-task=16
#SBATCH --time=12:00:00
#SBATCH --mail-type=FAIL

#SBATCH -p sandybridge

. /etc/profile.d/modules.sh
module purge
module load default-impi-LATEST

export OMP_NUM_THREADS=16
mpirun ./invertastic_lu --size 500000
